# -*- coding: utf-8 -*-
"""TAREA _ 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCBIf-xOUeGXrOVsBOrZnRCoLb-Sabjv
"""

data = {'Escuelas': ['San Diego' , 'Green House' , 'New Hope' , 'Trinity School'] ,
        'Director' : ['Silvia' , 'Marta' , 'Carlos' , 'Johana'] ,
        'Estudiantes' : [380, 230, 275, 162] }
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame(data)
print(df.head())

print(df.info())

print(df.describe())

plt.hist(df['Estudiantes'], bins=10)
plt.title('Distribución de estudiantes por escuela')
plt.xlabel('Número de estudiantes')
plt.ylabel('Frecuencia')
plt.show()

sns.boxplot(x='Escuelas', y='Estudiantes', data=df)
plt.title('Distribución de estudiantes por escuela')
plt.show()

"""¿Qué información te proporcionan los histogramas sobre la distribución de las
características? : En este caso los histogramas nos ofrecen una visión gráfica de la distribución de los estudiantes por escuela.
¿Qué patrones observas en los gráficos de pares?: Cada escuela tiene una cantidad similar de estudiantes, con pocas variaciones significativas entre ellas.
¿Cómo varía la distribución de las características entre las diferentes especies
según los gráficos de caja?:  No se observan escuelas con un número de estudiantes extremadamente alto o bajo en comparación con el resto

Conclusiones generales: podemos observar que las cuatro escuelas analizadas presentan una cantidad de estudiantes bastante similar. No hay una escuela que se destaque por tener una población estudiantil significativamente mayor o menor que el resto, teniendo en cuenta que las 4 escuelas analizadas están relativamente cerca, las 4 son privadas y por ende bilingues, con la leve diferencia de la cantidad de tiempo en el mercado.
Conclusiones específicas: Comportamiento de los datos: cierta homogeneidad en el tamaño de las instituciones, No encontramos escuelas con un número de estudiantes significativamente mayor o menor que el promedio. Esto indica una estabilidad general.
"""